stages:
  - build
  - deploy

variables:
  DEPLOY_USER: gitlab-runner
  DEPLOY_HOST: deployer.local

build-job:
  stage: build
  image: hugomods/hugo:exts-0.154.5
  script:
    - hugo --minify
  artifacts:
    paths:
      - public/
    expire_in: 1 hour

deploy-job:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - rsync -avz --delete public/ "${DEPLOY_USER}@${DEPLOY_HOST}:~/www/"

