stages:
  - build
  - deploy

build-job:
  stage: build
  image: hugomods/hugo:exts-0.154.5
  script:
    - hugo --minify
  artifacts:
    paths:
      - public/
    expire_in: 1 hour

deploy-job:
  stage: deploy
  only:
    - main
  script:
    - whoami
